package dt5202

import (
	"context"
	"fmt"
)

// CitirocReadbackHardware is the read-only extension needed to capture the
// stream generated by FPGA firmware after automatic ASIC configuration.
type CitirocReadbackHardware interface {
	CitirocHardware
	ReadRegister(context.Context, uint16, uint16, uint32) (uint32, error)
}

// ReadCitirocStream follows JANUS 5.0.0 ReadSCbsFromChip. It selects the ASIC,
// clocks its current configuration through the readback path, reads all 36
// words, and restores the original control register. It never enables manual
// stream loading (control bit 8).
func ReadCitirocStream(ctx context.Context, hw CitirocReadbackHardware, chain, node uint16, chip int) (stream CitirocStream, err error) {
	if chip < 0 || chip > 1 {
		return stream, fmt.Errorf("invalid Citiroc index %d", chip)
	}
	control, err := hw.ReadRegister(ctx, chain, node, uint32(CitirocSlowControl))
	if err != nil {
		return stream, fmt.Errorf("read Citiroc control: %w", err)
	}
	restore := func() {
		if restoreErr := hw.WriteRegister(ctx, chain, node, uint32(CitirocSlowControl), control); err == nil && restoreErr != nil {
			err = fmt.Errorf("restore Citiroc control: %w", restoreErr)
		}
	}
	defer restore()

	selection := uint32(chip) << 9
	if err = hw.WriteRegister(ctx, chain, node, uint32(CitirocSlowControl), selection); err != nil {
		return stream, fmt.Errorf("select Citiroc %d readback: %w", chip, err)
	}
	if err = hw.SendCommand(ctx, chain, node, uint32(CommandConfigureASIC), 0); err != nil {
		return stream, fmt.Errorf("clock Citiroc %d readback: %w", chip, err)
	}
	for word := range stream {
		if err = hw.WriteRegister(ctx, chain, node, uint32(CitirocSlowControl), selection|uint32(word)); err != nil {
			return stream, fmt.Errorf("select Citiroc %d readback word %d: %w", chip, word, err)
		}
		stream[word], err = hw.ReadRegister(ctx, chain, node, uint32(CitirocSlowData))
		if err != nil {
			return stream, fmt.Errorf("read Citiroc %d word %d: %w", chip, word, err)
		}
	}
	if stream[35]&0xff000000 != 0 {
		return stream, fmt.Errorf("Citiroc %d readback has nonzero bits beyond bit 1143: %#08x", chip, stream[35])
	}
	return stream, nil
}

// CompareCitirocStream performs a byte-exact comparison and reports the first
// differing stream bit as well as its containing word.
func CompareCitirocStream(expected, actual CitirocStream) error {
	for word := range expected {
		difference := expected[word] ^ actual[word]
		if difference == 0 {
			continue
		}
		for bit := 0; bit < 32; bit++ {
			if difference&(uint32(1)<<bit) != 0 {
				streamBit := word*32 + bit
				return fmt.Errorf("Citiroc stream bit %d differs in word %d: effective=%d requested=%d (effective word %#08x, requested word %#08x)", streamBit, word, (actual[word]>>bit)&1, (expected[word]>>bit)&1, actual[word], expected[word])
			}
		}
	}
	return nil
}

// VerifyCitirocReadback compares both FPGA-generated streams with the complete
// project-owned 1,144-bit representation.
func VerifyCitirocReadback(ctx context.Context, hw CitirocReadbackHardware, chain, node uint16, expected [2]CitirocChip) ([2]CitirocStream, error) {
	var captured [2]CitirocStream
	for chip := range expected {
		want, err := expected[chip].Stream()
		if err != nil {
			return captured, fmt.Errorf("construct Citiroc %d stream: %w", chip, err)
		}
		captured[chip], err = ReadCitirocStream(ctx, hw, chain, node, chip)
		if err != nil {
			return captured, err
		}
		if err = CompareCitirocStream(want, captured[chip]); err != nil {
			return captured, fmt.Errorf("Citiroc %d readback: %w", chip, err)
		}
	}
	return captured, nil
}

type CitirocProvenance string

const (
	CitirocDatasheetSemantics CitirocProvenance = "CITIROC1A datasheet V2.53 tables 5 and 7 define bit semantics"
	CitirocJANUSPolicy        CitirocProvenance = "JANUS 5.0.0 FERS_configure_5202.c hard-coded policy"
	CitirocFPGAOwned          CitirocProvenance = "DT5202 FPGA automatic stream generator; value requires hardware readback"
)

// CitirocPowerField records the provenance of every enable/power-mode bit.
// Expected is nil where the host sources do not establish the FPGA value.
type CitirocPowerField struct {
	Name       string            `json:"name"`
	Bit        int               `json:"bit"`
	Semantics  CitirocProvenance `json:"semantics"`
	ValueOwner CitirocProvenance `json:"value_owner"`
	Expected   *bool             `json:"expected,omitempty"`
}

// CitirocPowerProvenance is deliberately exhaustive. The datasheet provides
// meaning and position, but no reset/default stream. JANUS directly fixes only
// OTAForceOn; all other automatic-load values are owned by FPGA firmware and
// must be learned from an authoritative stream capture.
func CitirocPowerProvenance() []CitirocPowerField {
	fields := []struct {
		name string
		bit  int
	}{
		{"PowerEnableChargeDiscriminator", 256}, {"PowerModeChargeDiscriminator", 257},
		{"PowerEnableTimeDiscriminator", 259}, {"PowerModeTimeDiscriminator", 260},
		{"PowerEnableChargeFineDAC", 261}, {"PowerModeChargeFineDAC", 262},
		{"PowerEnableTimeFineDAC", 263}, {"PowerModeTimeFineDAC", 264},
		{"PowerModeTrackHoldHigh", 297}, {"PowerEnableTrackHoldHigh", 298},
		{"PowerModeTrackHoldLow", 299}, {"PowerEnableTrackHoldLow", 300},
		{"PowerModePeakHigh", 302}, {"PowerEnablePeakHigh", 303},
		{"PowerModePeakLow", 304}, {"PowerEnablePeakLow", 305},
		{"PowerModeFastShaperFollower", 310}, {"PowerEnableFastShaper", 311}, {"PowerModeFastShaper", 312},
		{"PowerModeLowShaper", 313}, {"PowerEnableLowShaper", 314},
		{"PowerModeHighShaper", 318}, {"PowerEnableHighShaper", 319},
		{"PowerModeHighPreamplifier", 324}, {"PowerEnableHighPreamplifier", 325},
		{"PowerModeLowPreamplifier", 326}, {"PowerEnableLowPreamplifier", 327},
		{"EnableInputDAC", 329}, {"PowerModeTemperature", 1099}, {"PowerEnableTemperature", 1100},
		{"PowerModeBandgap", 1101}, {"PowerEnableBandgap", 1102},
		{"PowerEnableChargeDAC", 1103}, {"PowerModeChargeDAC", 1104},
		{"PowerEnableTimeDAC", 1105}, {"PowerModeTimeDAC", 1106},
		{"PowerEnableHighOTA", 1127}, {"PowerModeHighOTA", 1128},
		{"PowerEnableLowOTA", 1129}, {"PowerModeLowOTA", 1130},
		{"PowerEnableProbeOTA", 1131}, {"PowerModeProbeOTA", 1132},
		{"OTAForceOn", 1133}, {"PowerEnableValidation", 1134}, {"PowerModeValidation", 1135},
		{"PowerEnableReset", 1136}, {"PowerModeReset", 1137},
		{"EnableDigitalOutput", 1138}, {"EnableOR32", 1139}, {"EnableOpenCollectorOR32", 1140},
		{"EnableOpenCollectorTimeOR", 1142}, {"EnableChannelTriggers", 1143},
	}
	answer := make([]CitirocPowerField, 0, len(fields))
	for _, field := range fields {
		entry := CitirocPowerField{Name: field.name, Bit: field.bit, Semantics: CitirocDatasheetSemantics, ValueOwner: CitirocFPGAOwned}
		if field.name == "OTAForceOn" {
			value := true
			entry.ValueOwner, entry.Expected = CitirocJANUSPolicy, &value
		}
		answer = append(answer, entry)
	}
	return answer
}

func CitirocManualLoadingVerified() bool { return false }
